name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            compiler: g++
          - os: windows-latest
            compiler: msvc
          - os: macos-latest
            compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.20'

    - name: Setup MSVC (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: cmake -B build -G "Visual Studio 16 2019" -A x64

    - name: Configure CMake (Unix)
      if: runner.os != 'Windows'
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      run: ctest --test-dir build --output-on-failure

    - name: Test CLI (Unix)
      if: runner.os != 'Windows'
      run: |
        ./build/cli/names
        ./build/cli/names 3
        ./build/cli/names --number
        ./build/cli/names 2 --number
        ./build/cli/names --version

    - name: Test CLI (Windows)
      if: runner.os == 'Windows'
      run: |
        .\build\cli\Release\names.exe
        .\build\cli\Release\names.exe 3
        .\build\cli\Release\names.exe --number
        .\build\cli\Release\names.exe 2 --number
        .\build\cli\Release\names.exe --version